azure-pipelines.yml
The Azure Pipelines trigger is only intended to be run manually. However, it's always being run when a PR is created, wasting time and resources. Specifying `trigger: none` was intended to address this, but it doesn't seem to be sufficient.
Trying to follow the guidelines here and add `pr: none` to azure-pipelines.yaml: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#opting-out-of-pr-validation
=> Disable PR triggers in Azure Pipelines

CHANGELOG.md, src/DurableTask.SqlServer/Scripts/drop-schema.sql, src/DurableTask.SqlServer/Scripts/logic.sql, src/DurableTask.SqlServer/Scripts/permissions.sql, src/DurableTask.SqlServer/Scripts/schema-0.2.0.sql, src/common.props
This is SQL function intended to be used by external scalers, like the [KEDA mssql scaler](https://keda.sh/docs/scalers/mssql/). The result represents the maximum number of instances needed to process the current workload (maximum assuming that each orchestration event and/or task activity needs to be handled by one instance).
Also:
- Updated package versions to 0.7.0
- Reverted default task hub behavior to use the user ID
- Fixed formatting bugs in CHANGELOG.md
=> Added dt.GetScaleMetrics scalar SQL function

src/DurableTask.SqlServer/DTUtils.cs, src/DurableTask.SqlServer/Scripts/logic.sql, src/DurableTask.SqlServer/Scripts/schema-0.2.0.sql, src/DurableTask.SqlServer/SqlTypes/TaskEventSqlType.cs, src/DurableTask.SqlServer/SqlUtils.cs, test/DurableTask.SqlServer.Tests/Integration/Orchestrations.cs, test/DurableTask.SqlServer.Tests/Utils/TestService.cs
@cgillum 
this PR adds support for versioned tasks (activities). Changes are similar to #11 in many ways.
Please provide feedback at your convenience.
Thank you!
=> Versioning support for tasks

docs/quickstart.md, src/DurableTask.SqlServer/DTUtils.cs, test/PerformanceTests/Common.cs, test/PerformanceTests/ManyMixedOrchestrations.cs, test/PerformanceTests/ManySequences.cs, test/PerformanceTests/PurgeOrchestrationData.cs
Extension version tracing is changed such that we only include the commit hash in debug mode. This is mainly to make traces less noisy for production scenarios. The commit hash also becomes less useful in those cases since the release will be properly tagged.
Regarding the performance test code, this PR adds a new function that purges all the orchestration from the database. This is useful for ensuring that each test starts from a clean slate in terms of how much data is in the database (which could otherwise impact things like query plans depending on in what order the tests are run). I've also added the ability to add a custom prefix to each of the created orchestration instances, making them easier to distinguish and query when running multiple tests in succession.
Lastly, updated the …
=> Improvements to perf-testing code and extension version tracing

src/DurableTask.SqlServer.AzureFunctions/ManagedIdentityOptions.cs, src/DurableTask.SqlServer.AzureFunctions/SqlDurabilityOptions.cs, src/DurableTask.SqlServer/DurableTask.SqlServer.csproj, src/DurableTask.SqlServer/ManagedIdentitySettings.cs, src/DurableTask.SqlServer/SqlConnectionFactory.cs, src/DurableTask.SqlServer/SqlDbManager.cs, src/DurableTask.SqlServer/SqlOrchestrationService.cs, src/DurableTask.SqlServer/SqlOrchestrationServiceSettings.cs
These changes are to resolve issue #18
=> Azure Managed Identity support - first version

CHANGELOG.md, docs/quickstart.md, docs/sidebar.md, src/DurableTask.SqlServer.AzureFunctions/AssemblyInfo.cs, src/DurableTask.SqlServer.AzureFunctions/DurableTask.SqlServer.AzureFunctions.csproj, src/DurableTask.SqlServer.AzureFunctions/SqlDurabilityProviderExtensions.cs, src/DurableTask.SqlServer.AzureFunctions/SqlDurabilityProviderFactory.cs, src/DurableTask.SqlServer/DurableTask.SqlServer.csproj, src/common.props, test/DurableTask.SqlServer.AzureFunctions.Tests/IntegrationTestBase.cs
Resolves #30
This PR adds an extension method to register the Durable Task SQL storage provider for Azure Functions (and Azure Web Jobs).
Here is an example of how we register the SQL provider in our integration tests.
```csharp
this.functionsHost = new HostBuilder()
.ConfigureLogging(
loggingBuilder =>
{
loggingBuilder.AddProvider(this.logProvider);
loggingBuilder.SetMinimumLevel(LogLevel.Information);
})
.ConfigureWebJobs(
webJobsBuilder =>
{
webJobsBuilder.AddDurableTask(options =>
{
options.StorageProvider["type"] = "mssql";
});
})
.ConfigureServices(
services =>
{
services.AddSingleton<INameResolver>(this.settingsResolver);
services.AddSingleton<IConnectionStringResolver>(this.settingsResolver);
services.AddSingleton<ITypeLocator>(this.typeLocator); …
```
=> Add extension methods for registering the SQL durability provider

CHANGELOG.md, src/DurableTask.SqlServer/Scripts/logic.sql, src/DurableTask.SqlServer/SqlOrchestrationService.cs, test/DurableTask.SqlServer.Tests/Integration/PurgeTests.cs, test/DurableTask.SqlServer.Tests/Utils/TestService.cs
The documentation for `PurgeOrchestrationHistoryAsync` says it should be purging instances that are older than the given threshold. However it seems that the stored procedure used to retrieve these is currently retrieving instances _newer_ than the given threshold.
This will PR fixes the `PurgeInstanceStateByTime` stored procedure to retrieve instances that are _older_ than the given threshold time.
=> Fix purge history threshold check

.github/workflows/build-and-test.yml, CHANGELOG.md, docs/quickstart.md, src/DurableTask.SqlServer/Scripts/logic.sql, src/DurableTask.SqlServer/Scripts/schema-0.2.0.sql, src/common.props, test/DurableTask.SqlServer.Tests/Integration/StressTests.cs
This PR fixes a common source of SQL deadlocks by removing foreign key constraints from the core tables. Not only does this resolve deadlocks, but some tests are showing significant performance improvements, helping justify this potentially controversial change.  As an example, a 2,000 sub-orchestration stress test went from taking >150 seconds to <40 seconds after this change. Comments have been added to the SQL schema file explaining why there are no FK constraints.
Data consistency will be enforced through careful use of transactions across the various stored procedures.
Resolves #45 
Resolves #23
Also:
* Minor documentation updates
* Incremented version to v0.10.1-beta
=> Removed foreign key constraints from all tables

src/DurableTask.SqlServer/Scripts/logic.sql
Per #51, this PR is a quick fix to unblock `CreateIfNotExstsAsync` running the `logic.sql` script.
=> Fix logic.sql Invalid Column usage

azure-pipelines.yml
This is to support the ESRP code signing pipeline we use for official releases. Our product doesn't depend on .NET Core 2.1, but the ESRP infrastructure we depend on unfortunately does. This change ensures we have both installed side-by-side.
=> Add .NET Core 2.1 support for build signing pipeline

CHANGELOG.md, src/DurableTask.SqlServer.AzureFunctions/DurableTask.SqlServer.AzureFunctions.csproj, src/common.props
Fixes https://github.com/microsoft/durabletask-mssql/issues/62
This PR simply adds `netstandard2.0` as a target for the Azure Functions extension. The DTFx package already supported `netstandard2.0`. No code changes were required.
=> Add support for .NET Standard 2.0 for Azure Functions

test/PerformanceTests/Dockerfile
The current sample Dockerfile doesn't work since the  PerformanceTest app is updgrade to the sdk 6.0.
=> fix the build issue of the Sample dockerfile for upgrading to sdk 6.0

src/DurableTask.SqlServer/Scripts/logic.sql, src/DurableTask.SqlServer/SqlOrchestrationService.cs, test/DurableTask.SqlServer.AzureFunctions.Tests/DurableTask.SqlServer.AzureFunctions.Tests.csproj, test/DurableTask.SqlServer.Tests/DurableTask.SqlServer.Tests.csproj
Resolves https://github.com/microsoft/durabletask-mssql/issues/69
The only relevant change is to logic.sql.  The others can be ignored.
With this very minimal fix, rows in the `dt.NewEvents` and `dt.NewTasks` tables can be as old as 68 _years_ (a significant improvement from 24 days).
=> Mitigate datediff overflow issue

src/DurableTask.SqlServer/DurableTask.SqlServer.csproj, src/DurableTask.SqlServer/Scripts/logic.sql, src/DurableTask.SqlServer/SqlUtils.cs
Hello
Here is a PR to retrieve the ParentInstance in GetOrchestrationStateAsync.
I noticed that this property is always null. This PR resolves the issue mentionned in this [link ](https://github.com/Azure/durabletask/issues/618) for mssql provider
=> retrieve ParentInstance in GetOrchestrationStateAsync

src/DurableTask.SqlServer.AzureFunctions/DurableTask.SqlServer.AzureFunctions.csproj, src/DurableTask.SqlServer/DurableTask.SqlServer.csproj
There was no reason for us to target .NET Standard 2.1, so for the GA release we want to remove this target and only support .NET Standard 2.0. This gives us maximum compatibility with a smaller package size and less opportunity for surprises.
=> Remove netstandard2.1 TFM

CHANGELOG.md, src/DurableTask.SqlServer/Scripts/logic.sql
Resolves #81
We were incorrectly raising an error from SQL if an activity task completes for an instance that's no longer running (e.g., a terminated instance). Because of this, we'd never delete the task-scheduled message, and it would re-execute continuously. This PR updates the `_CompleteTasks` sproc to handle this case correctly by ensuring we always delete the task-scheduled message.
While testing the fix, I also found an issue where we don't delete the task-scheduled message payloads after an activity completes (successfully or not), resulting in unreferenced payload data in the database (until the instance is purged). This is also fixed in this PR.
=> Fix problem terminating orchestration with running activity

.editorconfig, CHANGELOG.md, src/DurableTask.SqlServer/DTUtils.cs, src/DurableTask.SqlServer/EventPayloadMap.cs, src/DurableTask.SqlServer/Scripts/logic.sql, src/DurableTask.SqlServer/SqlOrchestrationService.cs, src/DurableTask.SqlServer/SqlTypes/HistoryEventSqlType.cs, src/DurableTask.SqlServer/SqlTypes/OrchestrationEventSqlType.cs, src/DurableTask.SqlServer/SqlTypes/TaskEventSqlType.cs, src/DurableTask.SqlServer/Utils/NetFxCompat.cs
Resolves #85 
Resolves #84 
This PR ensures that we always add a payload ID to the history table for events created by the orchestration. Previously, by default, these payload IDs were tracked temporarily in the NewEvents and NewTasks table, but then would get deleted, leaving behind orphan payloads in the database.  A previous PR cleaned up the orphan payloads (adding to the I/O cost of activity execution), but this PR reverts that change and does what I preferred to do, which is keep them there but ensure they are linked from the history table.
This also fixes an issue related to duplicate payloads being saved when input tracking is enabled on the TaskHubWorker.
=> Include more payload IDs in history table

src/DurableTask.SqlServer/Scripts/logic.sql
Resolves https://github.com/microsoft/durabletask-mssql/issues/100
The previous logic deleted payload data that was associated with the rows in the History table. In theory, this should "work" because there shouldn't be any payload data (besides custom status) that doesn't have an associated record in the History table. However, it seems that this isn't necessarily the case, or that we're losing track of certain payload IDs over time.
Regardless of the root cause for the previous issue, it makes sense to just purge all runtime data as part of ContinueAsNew. This PR does exactly that, ensuring that we can't run into this kind of problem in the future.
=> Delete all payload data on ContinueAsNew

CHANGELOG.md, docs/quickstart.md, docs/scaling.md, src/DurableTask.SqlServer.AzureFunctions/SqlDurabilityOptions.cs, src/DurableTask.SqlServer.AzureFunctions/SqlDurabilityProviderFactory.cs, src/DurableTask.SqlServer/DurableTask.SqlServer.csproj, test/DurableTask.SqlServer.AzureFunctions.Tests/IntegrationTestBase.cs, test/PerformanceTests/LongHaul.cs, test/PerformanceTests/Scripts/RunTestInAzure.ps1
This PR contains a small variety of changes for the v1.0.0 (GA) release.
* Update documentation to reflect latest performance numbers (throughput has gone up almost 4x since `v0.11.1-beta`!)
* Remove unnecessary nuget packages that were breaking Azure Functions V2 compatibility
* Replace deprecated IConnectionStringResolver usage with IConnectionInfoResolver to resolve build warnings (no behavior change)
* Add new *LongHaul* stress test to the performance testing project
* Add PowerShell script that I used for running performance tests in Azure
This is expected to be the last PR before the v1.0.0 (GA) stable release.
Fixes https://github.com/microsoft/durabletask-mssql/issues/107
=> Preparations for v1.0.0 (GA) release

src/DurableTask.SqlServer/Scripts/logic.sql
Change InstaceId variable to InstanceID so that sensitive databases can use the logic.sql script too.
=> Fixed script for case sensitive databases

src/DurableTask.SqlServer.AzureFunctions/DurableTask.SqlServer.AzureFunctions.csproj, src/DurableTask.SqlServer.AzureFunctions/SqlDurabilityProviderStartup.cs
Updating SqlDurabilityProviderStartup to implement IWebJobsStartup instead of FunctionsStartup. Similar PR merged in another Durable extension - https://github.com/microsoft/durabletask-netherite/pull/186
=> Updating SqlDurabilityProviderStartup to implement IWebJobsStartup

CHANGELOG.md, docs/architecture.md, docs/introduction.md, docs/multitenancy.md, src/DurableTask.SqlServer.AzureFunctions/DurableTask.SqlServer.AzureFunctions.csproj, src/DurableTask.SqlServer.AzureFunctions/SqlDurabilityProviderStartup.cs, src/DurableTask.SqlServer/Scripts/drop-schema.sql, src/DurableTask.SqlServer/Scripts/logic.sql, src/DurableTask.SqlServer/Scripts/permissions.sql, src/DurableTask.SqlServer/Scripts/schema-1.0.0.sql, src/DurableTask.SqlServer/SqlDbManager.cs, src/DurableTask.SqlServer/SqlOrchestrationService.cs, src/DurableTask.SqlServer/SqlOrchestrationServiceSettings.cs, src/DurableTask.SqlServer/SqlTypes/HistoryEventSqlType.cs, src/DurableTask.SqlServer/SqlTypes/MessageIdSqlType.cs, src/DurableTask.SqlServer/SqlTypes/OrchestrationEventSqlType.cs, src/DurableTask.SqlServer/SqlTypes/TaskEventSqlType.cs, src/DurableTask.SqlServer/SqlUtils.cs, src/common.props, test/DurableTask.SqlServer.Tests/Integration/DatabaseManagement.cs
Added multi-schema support for DTF Sql-Server as requested in #105.  Following the plan suggested by George, I've refactored the code to be able to use a custom schema name instead of the hardcoded "dt" as such:
-  Added a new property in SqlOrchestrationServiceSettings called SchemaName, defaulting to "dt"
- Modified all the scripts under /Scripts by replacing "dt" with a placeholder called {{SchemaNamePlaceholder}} and also added explicit table accessing by specifying the schemaName for each access.
- Added a new parameter to all xxxParameter methods from the SqlTypes files under /SqlTypes and from SqlUtils, called schemaName to be able to remove the hardcoded "dt".
- Modified the SqlDbManager such that before executing the script commands, it will replace the schemaNamePlaceholder with …
=> Added multi-schema support for DTF Sql-Server

docs/architecture.md, docs/multitenancy.md, docs/quickstart.md, src/DurableTask.SqlServer.AzureFunctions/SqlDurabilityOptions.cs, src/DurableTask.SqlServer/DurableTask.SqlServer.csproj, src/DurableTask.SqlServer/Scripts/drop-schema.sql, src/DurableTask.SqlServer/Scripts/logic.sql, src/DurableTask.SqlServer/Scripts/permissions.sql, src/DurableTask.SqlServer/Scripts/schema-1.0.0.sql, src/DurableTask.SqlServer/SqlDbManager.cs
With https://github.com/microsoft/durabletask-mssql/pull/110, IDEs like Visual Studio were no longer able to parse the SQL files because the `{{` and `}}` characters were not valid in many contexts.  This PR replaces `{{` and `}}` with `__` (double underscores) so that IDEs don't flag the placeholders as syntax errors.
With this change, I validated that I was able to execute all the .sql files directly against my local SQL database without doing any text substitution. We'll still do text substitution at runtime. This change is purely to simplify local development of the T-SQL code. 
This PR also adds support for custom schema names to Azure Functions via a new `schemaName` field in the host.json settings.
=> Rename SchemaNamePlaceholder and add Azure Functions support

CHANGELOG.md, src/DurableTask.SqlServer/Scripts/logic.sql, src/DurableTask.SqlServer/SqlOrchestrationService.cs, test/DurableTask.SqlServer.Tests/Integration/Orchestrations.cs, test/DurableTask.SqlServer.Tests/Utils/TestInstance.cs
Fixes https://github.com/microsoft/durabletask-mssql/issues/120
Note that this change may be breaking, depending on how exception handling logic is written. I suspect in most, if not all cases, the change from `InvalidOperationException` to `OrchestrationAlreadyExistsException` should be non-breaking, hence, I'm releasing this fix as part of a minor version update instead of a major version update.
=> Fixes for deduple behavior on orchestration create

CHANGELOG.md, docs/quickstart.md, src/DurableTask.SqlServer.AzureFunctions/DurableTask.SqlServer.AzureFunctions.csproj, src/DurableTask.SqlServer.AzureFunctions/SqlDurabilityProvider.cs, src/common.props
Several quick changes in this PR:
* Update Durable Functions extension dependency to v2.9
* Update Durable Functions quickstart docs to reflect latest language compatibility information
* Enable `SupportsImplicitEntityDeletion` for Durable Entities
* Set package version to have `-rc` suffix to enable a quick non-production reader release
=> Update Durable Functions extension dependency

DurableTask.SqlServer.sln, docs/quickstart.md, src/Functions.Worker.Extensions.DurableTask.SqlServer/Functions.Worker.Extensions.DurableTask.SqlServer.csproj, src/Functions.Worker.Extensions.DurableTask.SqlServer/Properties/AssemblyInfo.cs
This PR enables mssql usage in Azure functions dotnet isolated. 
- Adds a new project and nuget package `Microsoft.Azure.Functions.Worker.Extensions.DurableTask.SqlServer`, which has a single attribute that tells the host to load the `Microsoft.Azure.DurableTask.SqlServer.AzureFunctions` package.
- Customers will reference this package in their dotnet isolated projects (and _not_ `Microsoft.Azure.DurableTask.SqlServer.AzureFunctions`)
=> Add dotnet-isolated extensions package

src/DurableTask.SqlServer.AzureFunctions/SqlScaleMetric.cs, src/DurableTask.SqlServer.AzureFunctions/SqlScaleMonitor.cs
We are currently redesigning the scale controller to unify the duplicate scaling logic that resides in each of the extensions (CosmosDB, ServiceBus, EventHubs, Storage, etc.) and the scale controller. As a part of this redesign, scale controller will directly instantiate the ScaleMonitors for each of the above extensions, and call into the GetMetricsAsync and GetScaleStatus methods directly. To support this, we need to make ScaleMonitors, and any dependent classes public in each of the extensions. 
Resources:
- [Azure Functions Scale Controller Redesign.docx](https://microsoft.sharepoint.com/:w:/r/teams/Antares/Shared%20Documents/Functions/Azure%20Functions%20Scale%20Controller%20Redesign.docx?d=wf9ab8e165f9644229184af0bc429587b&csf=1&web=1&e=bpERSt)
- [Azure Functions WebJobs SDK scaling …
=> Make SqlScaleMonitor and SqlScaleMetric public for Scale Controller Redesign

src/DurableTask.SqlServer.AzureFunctions/SqlScaleMetric.cs, src/DurableTask.SqlServer.AzureFunctions/SqlScaleMonitor.cs
Reverts microsoft/durabletask-mssql#139
To incorporate new work by Alexey, we are instead creating IScalerFactory implementations across all extensions to keep the ScaleMonitors and Metrics internal
=> Revert "Make SqlScaleMonitor and SqlScaleMetric public for Scale Controller Redesign

docs/quickstart.md, src/Functions.Worker.Extensions.DurableTask.SqlServer/Functions.Worker.Extensions.DurableTask.SqlServer.csproj, src/Functions.Worker.Extensions.DurableTask.SqlServer/Properties/AssemblyInfo.cs
Two fixes:
1. Make sure assembly name and package name match (for consistency)
2. Add `enableImplicitRegistration = true` to the extension attribute.
- This is because our package has 0 binding attributes in it, the build task skips it unless this is set to `true`.
=> Fix Az Func dotnet-isolated extension

src/DurableTask.SqlServer/SqlOrchestrationService.cs, test/DurableTask.SqlServer.AzureFunctions.Tests/Utils.cs
Resolves #121 
Handling the case where `TimeSpan.MaxValue` or `TimeSpan.MinValue` are used for the timeout value in `WaitForOrchestrationAsync(...)`. In both cases, we treat it as meaning "no timeout".
=> Fix timeout arg exception in WaitForOrchestrationAsync

CHANGELOG.md, src/DurableTask.SqlServer/SqlOrchestrationService.cs, src/DurableTask.SqlServer/SqlUtils.cs, src/common.props, test/DurableTask.SqlServer.AzureFunctions.Tests/Utils.cs, test/DurableTask.SqlServer.Tests/Integration/StressTests.cs
…on  because of mssql client async bug [sqlcli](https://github.com/dotnet/SqlClient/issues/593)
It should be easy to switch back when the fix is done
It should also fix #126
=> Synchronous reads for improved performance for large payloads

CHANGELOG.md, src/DurableTask.SqlServer/SqlUtils.cs
Fixes #145 
The issue is specific to protobuf/gRPC serialization of history events used by Azure Functions .NET Isolated and Java. There was a `null` placeholder value for `SubOrchestrationInstanceCreatedEvent.InstanceId`, which was not compatible with the protobuf contract. The quick fix is to use `""` instead of `null`.
There is a potentially larger fix, which is to correctly rehydrate the instance ID value for this history event, but this would require a database schema change, which is a much more expensive process. Per testing, the workaround in this PR should be sufficient to unblock basic sub-orchestration usage.
=> Quick fix for sub-orchestration gRPC serialization issue

CHANGELOG.md, src/DurableTask.SqlServer/Scripts/logic.sql, test/DurableTask.SqlServer.AzureFunctions.Tests/CoreScenarios.cs, test/DurableTask.SqlServer.AzureFunctions.Tests/Functions.cs, test/DurableTask.SqlServer.Tests/Utils/SharedTestHelpers.cs
Fixes #146 
An issue was discovered where certain message payloads were being lost in certain situations. The root cause ended up being overaggressive purge logic in the SQL stored procedures when an orchestration (or entity) does a ContinueAsNew.
This PR updates the ContinueAsNew T-SQL logic to be more selective in what data it deletes to ensure that unprocessed events are not impacted. This PR also adds a new test-case that was previously able to reproduce the issue reliably.
=> Fix continue-as-new data corruption issue

.github/fabricbot.json
As in title. This will allow FabricBot to manage special labels like "needs: triage" and "needs: author response".
=> Add FabricBot config for automatic GitHub triaging

CHANGELOG.md, src/DurableTask.SqlServer/SqlOrchestrationService.cs, src/DurableTask.SqlServer/SqlOrchestrationServiceSettings.cs
I was analyzing the cost of an app service with overall low volume (1-2 orchestrations per week), and right now the cost of the app service telemetry outweighs the cost of the basic app service.
Since the orchestrations I run are very tolerable of delays, I wanted to increase the maximum backoff values here to 5 minutes or more for a ~99% reduction in unnecessary telemetry.
As the orchestrations I run are just a hobby project, I'm not as familiar with the potential consequences of changing these values, especially with how they relate to each other. But I found the todo in the repo and figured I would start with the most basic implementation of passing it through on the settings object.
=> Support configurable backoff intervals

CHANGELOG.md, src/DurableTask.SqlServer/BackoffPollingHelper.cs, src/DurableTask.SqlServer/SqlOrchestrationService.cs, src/DurableTask.SqlServer/SqlOrchestrationServiceSettings.cs
PR for #172. Makes the minimum and delta backoff intervals configurable for both activity and orchestration instance polling. For situations where a lot of pods have TaskHubWorkers, the default poll interval of 50ms uses a significant amount of DTU. This can become more prominent when SQL Azure decides to change the query plan due to parameter sniffing. In production, we see 12 polls per second on NewTasks and Instances tables each during averaged over 24 hours.
A behavior we've seen that you might be able to confirm @cgillum is on new task polling. It appears that the behavior of activities scheduled by an orchestration are inserted to the NewTasks table with a lock. The TaskHubWorker that is running the orchestration instance is then also expected to run the activities and only after …
=> Adds config for min and delta backoff poll intervals

CHANGELOG.md, src/DurableTask.SqlServer.AzureFunctions/DurableTask.SqlServer.AzureFunctions.csproj, src/DurableTask.SqlServer/DTUtils.cs, src/DurableTask.SqlServer/DbTaskEvent.cs, src/DurableTask.SqlServer/SqlOrchestrationService.cs, src/DurableTask.SqlServer/SqlUtils.cs, test/DurableTask.SqlServer.Tests/Integration/DatabaseManagement.cs, test/DurableTask.SqlServer.Tests/Integration/LegacyErrorPropagation.cs, test/DurableTask.SqlServer.Tests/Integration/Orchestrations.cs, test/DurableTask.SqlServer.Tests/Utils/TestService.cs
Resolves https://github.com/microsoft/durabletask-mssql/issues/161
For whatever reason, we forgot to fully implement exception propagation in this MSSQL backend for the Durable Task Framework. Fundamentally, the reason this is easy to miss is because the MSSQL provided doesn't serialize history events, but rather manually reads and writes them into structured SQL tables.
In this PR, we implement handling for both `ErrorPropagationMode.SerializeExceptions` (which we call "legacy") and `ErrorPropagationMode.UseFailureDetails` (which I'm treating as the new default).
To summarize the changes in this PR, we:
* Make sure to read/write failure details to and from the database as JSON
* Make sure we surface error details in the right way in the public API
* Add new tests or improve existing …
=> Fix error handling propagation

CHANGELOG.md, src/DurableTask.SqlServer/Scripts/logic.sql, src/DurableTask.SqlServer/SqlOrchestrationService.cs, src/DurableTask.SqlServer/SqlUtils.cs, src/common.props, test/DurableTask.SqlServer.Tests/Integration/DatabaseManagement.cs, test/DurableTask.SqlServer.Tests/Integration/Orchestrations.cs, test/DurableTask.SqlServer.Tests/Utils/TestInstance.cs
Fixes https://github.com/microsoft/durabletask-mssql/issues/181
The MSSQL backend was missing support for suspend/resume. It also made some bad assumptions about how it would eventually behave when introduced, so some existing logic needed to be removed.
I also bundled a couple additional minor fixes into this PR:
* Fixed inconsistent exception throwing in SqlOrchestrationService.WaitForOrchestrationAsync (realized this was a problem while writing my suspend/resume test)
* Fixed minor issue with default DateTime handling (force it to always be UTC) - this is an issue with certain kinds of serializers, like protobuf, which reject DateTime values that aren't explicitly UTC (found this doing some unrelated exploratory prototyping).
=> Implement support for suspend/resume

src/DurableTask.SqlServer/SqlUtils.cs
Fixes https://github.com/microsoft/durabletask-mssql/issues/198.
The other issue that resulted in this InvalidCastException is caused by https://github.com/Azure/durabletask/pull/1018. This PR removes the root cause of the issue, which was that we're not correctly round-tripping event IDs for some history events (one of the downsides of custom event serialization). DurableTask.Core was making certain assumptions about the values of event IDs that weren't valid due to this bug.
=> Fix SQL roundtrip issue for history event IDs

.github/workflows/build-and-test.yml, CHANGELOG.md, src/Functions.Worker.Extensions.DurableTask.SqlServer/Properties/AssemblyInfo.cs, src/common.props, test/DurableTask.SqlServer.Tests/Integration/DatabaseManagement.cs, test/DurableTask.SqlServer.Tests/Integration/Orchestrations.cs
Updating versions prior to doing a patch release.
Also fixes an inconsistency where the .NET Isolated project was incorrectly referencing the v1.1.* version of the WebJobs package when it should have been referencing the v1.2.* versions.
=> Increment versions (to v1.2.2)

CHANGELOG.md, src/Functions.Worker.Extensions.DurableTask.SqlServer/Functions.Worker.Extensions.DurableTask.SqlServer.csproj, src/Functions.Worker.Extensions.DurableTask.SqlServer/Properties/AssemblyInfo.cs, src/common.props, test/DurableTask.SqlServer.Tests/Integration/DatabaseManagement.cs
Resolves https://github.com/microsoft/durabletask-mssql/issues/212
This PR does two things:
- Removes the usage of version globs when referencing the WebJobs extension (see #212).
- Removes the need to update hardcoded strings by putting this version configuration into the build.
Note that we're including this pas part of a 1.3.x release since only 1.2.x versions are affected by the version glob issue.
=> Replace hardcoded version string + globs with build variables

CHANGELOG.md, src/DurableTask.SqlServer/Scripts/logic.sql
Added missing Rollback transaction
#218
=> Added missing Rollback transaction

nuget.config
This is the DTFx-MSSQL version of this PR: https://github.com/Azure/azure-functions-durable-extension/pull/2842
As part of the 1ES migration, we have new supply chain requirements around our repo's nuget.config files.
In particular, we're getting errors due to use MyGet. This PR removes our MyGet usage. It also addresses warnings regarding missing `<clear/>` statements.
=> Clear NuGet security warnings

CHANGELOG.md, src/DurableTask.SqlServer/SqlUtils.cs
Pass the DBCommand to the SqlUtils.WithRetry() method and let the method check the DBCommand connection state and open if needed before attempting the next attempt. This way, we avoid throwing an Error back when there is a intermittent network connectivity issue.
=> Fix SqlUtils.WithRetry() to open a new connection if the last attempt closed the connection due to network issues.

.github/workflows/build-and-test.yml, docs/kubernetes.md
As we're migrating to 1ES, we now have a credentials scanner in our repo that's flagging the example DB password in our docs.
The keyword 'PLACEHOLDER' tells credscanner to ignore these "fake secrets", so this PR updates our example passwords to read "PLACEHOLDER" instead of giving a concrete password.
=> Use 'PLACEHOLDER' to represent secrets in docs and GH workflows

docs/taskhubs.md
It appears there was a mistake in one of the code samples in the documentation, showing "MicrosoftSQL" as the `storageProvider/type` value in host.json when it should actually be "mssql". This commit fixes the doc mistake.
=> Update taskhubs.md with correct storageProvider type value

docs/kubernetes.md, docs/quickstart.md, test/setup.ps1
In [this PR](https://github.com/microsoft/durabletask-mssql/pull/235) the CI is failing because the `sqlcmd` utility cannot be found under `/opt/mssql-tools/bin/sqlcmd`.
We had discovered a similar issue in the MSSQL E2E test of the DF Extension a few weeks back. The issue is newer versions of the MSSQL docker image now place `sqlcmd` inside `/opt/mssql-tools18/bin/`.
This PR updates the `sqlcmd` reference to reflect this change.
=> Fix CI: update sqlcmd to new location: /opt/mssql-tools18

Directory.Build.targets, DurableTask.SqlServer.sln
When building in 1ES, source-link information gets lost due to the code-mirror'ing. This creates issues during debugging, as Visual Studio would be unable to determine where to download the source code from. This PR aims to fix that by following conventions set by the Azure Functions Host.
This is the durabletask-dotnet version of this DTFx PR: https://github.com/Azure/durabletask/pull/1147
=> Add sourcelink reconstruction task in msbuild

eng/ci/publish.yml
I made a copy-pasting error in the PR that introduced the publishing pipeline - it was grabbing the nupkgs from the durabletask-dotnet.official pipeline, not durabletask-mssql.official. This PR fixes that.
=> Rename source artifacts pipeline for publishing pipeline

CHANGELOG.md, src/DurableTask.SqlServer.AzureFunctions/DurableTask.SqlServer.AzureFunctions.csproj, src/DurableTask.SqlServer/DurableTask.SqlServer.csproj, src/common.props, test/DurableTask.SqlServer.Tests/Integration/DatabaseManagement.cs
As titled. This PR updates the below dependencies to start the durabletask mssql backend v1.5.0 release:
Microsoft.Azure.WebJobs.Extensions.DurableTask 2.13.7 -> 3.0.0
Microsoft.Azure.DurableTask.Core 2.*-> 3.*
=> Update Durabletask Dependencies for v1.5.0 Release
